apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aisec.fullname" . }}-config
  labels:
    {{- include "aisec.labels" . | nindent 4 }}
data:
  AISEC_LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  AISEC_REPORT_OUTPUT_DIR: {{ .Values.config.reportOutputDir | quote }}
  AISEC_REPORT_FORMATS: {{ .Values.config.reportFormats | quote }}
  AISEC_REPORT_LANGUAGE: {{ .Values.config.reportLanguage | quote }}
  AISEC_FALCO_ENABLED: {{ .Values.config.falcoEnabled | quote }}
  AISEC_CLOUD_STORAGE_BACKEND: {{ .Values.config.cloudStorageBackend | quote }}
  AISEC_CLOUD_STORAGE_BUCKET: {{ .Values.config.cloudStorageBucket | quote }}
  AISEC_CLOUD_STORAGE_PREFIX: {{ .Values.config.cloudStoragePrefix | quote }}
