apiVersion: v1
kind: ServiceAccount
metadata:
  name: aisec
  labels:
    app.kubernetes.io/name: aisec
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aisec-role
  labels:
    app.kubernetes.io/name: aisec
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aisec-rolebinding
  labels:
    app.kubernetes.io/name: aisec
subjects:
  - kind: ServiceAccount
    name: aisec
roleRef:
  kind: Role
  name: aisec-role
  apiGroup: rbac.authorization.k8s.io
